### ISSUE TITLE
Interpolate based on gdp

### ISSUE THREAD

**Issue by gregmacfarlane** [gregmacfarlane/trucksim_disagg#12]
Currently we create a 2011 scenario by linearly interpolating between 2007 data and 2015 forecasts. It would be better to grow to 2011 (or any year from 2007 to the present) based on observed economic 
patterns in the interim years.

**Comment by gregmacfarlane** [comment]
The recession of 2007-2009 and the slow recovery will certainly have affected this growth, as will the mining of shale gas beginning around 2010. What if all commodities track national GDP except for oil and gas, which we can find information for elsewhere?

**Comment by gregmacfarlane** [comment]
Let's use [this table](http://www.bea.gov/iTable/iTable.cfm?ReqID=51&step=1#reqid=51&step=51&isuri=1&5114=a&5102=15).

**Comment by gregmacfarlane** [comment]
From @rickdonnelly:

> So assuming all that is correct I started thinking about how you might do some sort of weighted or scaled interpolation instead of linear approximation. If you had a longer time series of GDP (easily obtainable) prior to 2007 and the FAF extending out to 2040 you should be able to fit some sort of simple polynomial to the combined data that would enable you to mimic the cyclical patterns in the middle. I have a time series forecasting textbook somewhere that has that example in it, but not here at the office. But the gist is that you normalize both curves (as you’ve done here?) and then scale one to the other. Sort of like plotting them both on mylar and then moving them around until you get the overlay that you’re wanting. I think the book said that you could do a log transform on the y axis to make it easier, but I’m not sure that it makes much difference.

**Comment by gregmacfarlane** [comment]
I guess I'm not sure why this would be preferable to just applying the observed indexed factor; unless, of course you're looking further into the future. But then I think the long-term trend would work back out.

**Comment by rickdonnelly** [comment]
If you're only worried about lining up the FAF flows with the GDP over the years shown I agree that you could probably easier scale the eight years shown using the ratio you've computed. But if you're looking for evidence for treating 2008 as an outlier you'd need a long time series than what you've shown here. Indeed, if you're looking at growth over the eight-year period it would appear that linear approximation gets it right. You'd only care about the fluctuations unless you were trying to zero in on 2008, which at this point in time seems to be further back than I'd care about.

**Comment by gregmacfarlane** [comment]
I improved the code infrastructure to interpolate between 2007 and 2015, along with various other improvements. If we think that a linear interpolation is actually better, then we implement it in another issue.

**Comment by gregmacfarlane** [comment]
Linear interpolation is working in [b393407](inhttps://github.com/gregmacfarlane/trucksim_disagg/commit/b393407829fbb7cde3b5556f2c06228236bc2977)
